### ISSUE TITLE
debug keys

### ISSUE THREAD

**Issue by yahav36** [GoogleWorkShop/Petti#92]
"c:\Program Files\Java\jdk1.7.0_71\bin\keytool.exe" -exportcert -list -v -alias androiddebugkey -keystore c:\Users\yahav\.android\debug.keystore -storepass android

**Comment by razmay89** [comment]
E9:0B:11:C7:2A:C2:C6:73:09:C5:F1:6F:D6:6C:D4:AB:C4:54:30:4A
